name: passtop
description: A password managing application made with Flutter and Supabase.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # UI
  flutter_svg: ^2.0.6
  animate_do: ^3.0.2
  flutter_remix: ^0.0.3
  loading_animation_widget: ^1.2.0+4
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  flutter_easyloading: ^3.0.5
  flutter_native_splash: ^2.3.0
  custom_navigation_bar: ^0.8.2
  flutter_typeahead: ^4.6.2

  # Backend
  supabase_flutter: ^1.10.0

  # State Management
  get: ^4.6.5

  # Utils
  flutter_screenutil: ^5.8.4
  flutter_dotenv: ^5.0.2
  uuid: ^3.0.7
  connectivity_plus: ^4.0.1
  http: ^1.1.0
  crypto: ^3.0.3
  encrypt: ^5.0.1
  pointycastle: ^3.7.3
  convert: ^3.1.1
  flutter_appauth: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/fonts/
    - assets/images/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
